# Fonctions de plusieurs variables

# TP 1

## 1. Bases, fonctions

1. Écrire le programme `cylindre.py` : il contient une fonction qui, appelée après saisie d’un rayon et d’une
hauteur, calcule le volume d’un cylindre droit.

In [1]:
%%writefile cylindre.py
import numpy as np

def cylindre(r:float, h:float)->float :
    return np.pi*(r**2)*h

Overwriting cylindre.py


In [2]:
from cylindre import cylindre

cylindre(10, 5)

1570.7963267948967

2. Écrire le programme `parite.py` : l’utilisateur est invité à entrer un nombre entier ; le programme contient une fonction qui teste la parité du nombre ; le résultat est affiché.

In [3]:
%%writefile parite.py

def parite(n:int)->bool :
    return n%2==0

if __name__ == "__main__" :
    n=int(input())
    print(parite(n))

Overwriting parite.py


In [4]:
from parite import parite

parite(10)

True

In [5]:
parite(13)

False

## 2. Boucles

1. Écrire le programme `classement.py` :
    1. après saisie de 2 nombres, il sort le min.
    2. après saisie de 2 chaines de caractères, il sort la plus longue ou, quand c’est le cas, annonce qu’elles ont la même longueur.

In [6]:
%%writefile classement.py

def classement(entry1, entry2):
    #cas où on donne deux chaines de caractères
    if type(entry1)==type(entry2)==str :
        if len(entry1)>len(entry2) :
            return entry1
        elif len(entry1)<len(entry2) :
            return entry2
        else :
            return "les deux chaînes de caractères sont de la même longueur"
    
    #cas où l'on donne deux nombres
    elif type(entry1) in [float, int] and type(entry2) in [float, int]:
        if entry1 < entry2 :
            return entry1
        else :
            return entry2
    
    else :
        raise TypeError(f"les entrées doivent êtres de types (int ou float, int ou float) ou (str, str) et pas ({type(entry1).__name__}, {type(entry2).__name__})")

Overwriting classement.py


In [7]:
from classement import classement
import numpy as np

classement(1, np.pi)

1

In [8]:
classement("never gonna","give you up")

'les deux chaînes de caractères sont de la même longueur'

2. Écrire un programme `FanDeTrump.py` qui affiche 100 fois : "Je voudrais pouvoir voter pour Donald Trump".

In [9]:
%%writefile FanDeTrump.py

#on peut faire un programme simple qui utilise une boucle for :
for i in range(100):
    print("Je voudrais pouvoir voter pour Donald Trump")

#sinon peut utiliser le caractère spécial de retour à la ligne à notre avantage et éviter d'avoir à faire une boucle :
#print("Je voudrais pouvoir voter pour Donald Trump\n"*100)

Overwriting FanDeTrump.py


3. Écrire un programme `DeuxADeux.py` qui affiche les nombres de 2 en 2 jusqu’à 100, d’abord en utilisant
un for puis en utilisant un while.

In [10]:
%%writefile DeuxADeux.py
#avec une boucle for

for i in range(0,101,2): #on s'arrête à 101 car range(0,n) exclut la valeur n en s'arrêtant à n-1
    print(i)

Overwriting DeuxADeux.py


In [11]:
%%writefile -a DeuxADeux.py
#avec une boucle while

i=0
while i<=100 :
    print(i)
    i+=2

Appending to DeuxADeux.py


## 3. Listes

1. Faire une liste contenant les mots *Hulk, Choquet, Superman, Tyson, DarkVador*. Afficher les éléments
de la liste (hors de la liste). Puis les afficher classés selon leur puissance (penser au classement naturel par
ordre alphabétique).

In [12]:
Noms = ["Hulk", "Choquet", "Superman", "Tyson", "DarkVador"]

In [13]:
def afficher(L:list):
    for elt in L :
        print(elt)

In [14]:
afficher(Noms)

Hulk
Choquet
Superman
Tyson
DarkVador


In [15]:
def trier(L:list)->list:
    #transforme une lettre en un entier correspondant à son rang dans l'alphabet : a->0, b->1, ...
    def val(c:chr)->int:
        if c.isalpha() :
            return ord(c.upper())-65
        else :
            raise TypeError(f"le caractère donné {c} n'est pas alphabétique")
    
    #revoie true si le premier mot 'm1' est plus petit que le mot 'm2' selon l'ordre alphabétique, false sinon
    def lt(m1:str,m2:str)->bool:
        for i in range(min(len(m1),len(m2))):
            if val(m1[i])<val(m2[i]) :
                return True
            elif val(m1[i])>val(m2[i]) :
                return False
        return len(m1)<=len(m2)

    #j'utilise l'algorithme de tri développé dans la partie 6
    def tri_sélection(L:list)->list:
        for i in range(len(L)-1):
            i_min = i
            for j in range(i+1, len(L)):
                if lt(L[j],L[i_min]) :
                    i_min = j
            L[i], L[i_min] = L[i_min], L[i]
        return L
    tri_sélection(L)
    

In [16]:
trier(Noms)

In [17]:
afficher(Noms)

Choquet
DarkVador
Hulk
Superman
Tyson


2. Écrire un programme `loto.py` :
    * Le programme fait un tirage de 6 numéros (entiers bien sûr au loto) entre 1 et 49.
    * L’utilisateur choisit un 1er numéro entre 1 et 49.
    * On vérifie d’abord s’il a gagné en tenant compte de l’ordre (PMU...), puis s’il a gagné sans tenir compte de l’ordre (loto...).

Pensez à ajouter un affichage à la fin pour vérifier que la Rochelaise des Jeux n’a pas triché. Compléter avec
un jeu à 6 paris.

In [18]:
%%writefile loto.py
import numpy as np

np.random.seed(69) #le tirage sera 12-10-46-29-23-26
def tirage(essais:int):
    V = [i for i in range(1,49)]
    T = [V.pop(np.random.randint(len(V))) for i in range(6)]
    E = []
    if not 0<essais<7 :
        raise ValueError("le nombre d'essais doit être compris entre 1 et 6 inclus")
    for i in range(essais):
        n = int(input(f"entrez votre nombre ({i+1}) : "))
        if not 0<n<50 :
            raise ValueError("Vous devez donner un nombre entier entre 1 et 49 inclus")
        if n in E :
            raise ValueError("Vous ne pouvez pas donner deux fois le même nombre")
        E.append(n)
    G = ["perdu", "gagné"]
    print(f"Vous avez {G[int(E==T[:len(E)])]} au PMU")
    print(f"Vous avez {G[set(E)<=set(T)]} au LOTO")
    print("-".join([str(t) for t in T]))

Overwriting loto.py


In [19]:
from loto import tirage

tirage(6)

entrez votre nombre (1) : 12
entrez votre nombre (2) : 10
entrez votre nombre (3) : 46
entrez votre nombre (4) : 29
entrez votre nombre (5) : 23
entrez votre nombre (6) : 26
Vous avez gagné au PMU
Vous avez gagné au LOTO
12-10-46-29-23-26


## 4. Communiquer avec l’au-delà de Python

1. Écrire un programme `lire_fichier.py` qui lit le fichier `machin.txt` et l’affiche.

In [20]:
%%writefile lire_fichier.py

with open("machin.txt", "r") as f :
    print(f.read())

Overwriting lire_fichier.py


In [21]:
%run -i lire_fichier.py

                                                                
                      ##                                        
                      #:#                       ###             
                      #:#                     ##:::#            
                      #=:#                   #::***#            
                      #=:#                  #:=*=**:#           
                      #*=:#                #:=*===**#           
                      #*==:#              #:=*=====*#           
                     #***==:##           #:=*======*#           
                     #***##==:#######   #:=*====*===#           
                     #*##***==::===::###:==*===***==#           
                    #:***============::==**==****==*#           
                  ##:=========:==:::===#=======**==*#           
                ##:===.====*=======::===#=====**==*:#           
              ##::===.:.==*=============:#===***==*:#           
             #::===..:::=

2. Créer un fichier `interessant.txt` puis le remplir (avec un mot par ligne) à partir de la liste suivante :
’ce’ ’fichier’ ’est’ ’sans’ ’intérêt’

Puis ajouter à ce fichier "vraiment sans intérêt".

In [22]:
with open("intéressant.txt", "w", encoding='utf-8') as f :
    Mots = ['ce', 'fichier', 'est', 'sans', 'intérêt']
    for m in Mots :
        f.write(m+"\n")

In [23]:
with open("intéressant.txt", "a", encoding='utf-8') as f :
    f.write("vraiment sans intérêt\n")

3. Une remarque sur les modules (que vous créez) :
Il est possible de tester les modules écrits directement en utilisant `if __name__ == "__main__" :` (vous le
verrez parfois dans les programmes).

Exemple : Créez un fichier `sanstitre1.py` contenant :

In [24]:
%%writefile sanstitre1.py

import math

def Aire_Cercle (rayon) :
    return (math.pi * rayon * rayon )
def Perimetre_Cercle (rayon) :
    return (2 * math.pi * rayon)
if __name__ == "__main__" :
    r = int (input ("Votre rayon : "))
    print ("Aire : %f" % (Aire_Cercle (r)))
    print ("Perimetre : %f" % (Perimetre_Cercle (r)))

Overwriting sanstitre1.py


puis créez un fichier `sanstitre2.py` avec

In [25]:
%%writefile sanstitre2.py

from sanstitre1 import *
r = int (input ("Votre rayon : "))
print ("Aire : %f" % (Aire_Cercle (r)))
print ("Perimetre : %f" % (Perimetre_Cercle (r)))

Overwriting sanstitre2.py


In [26]:
%run -i sanstitre1

Votre rayon : 1
Aire : 3.141593
Perimetre : 6.283185


In [27]:
%run -i sanstitre2

Votre rayon : 2
Aire : 12.566371
Perimetre : 12.566371


## 5. Classes

1. Créer une classe CunCercle (dans un fichier `OuiCunCercle.py`) qui se définit par le rayon. La classe
CunCercle devra aussi permettre de calculer l’aire du cercle. Et utiliser cette classe dans un autre fichier.

In [28]:
%%writefile OuiCunCercle.py
import numpy as np

class CunCercle :
    def __init__(self, r:float):
        self.r = r

    def aire(self)->float:
        return float(np.pi*self.r**2)

Overwriting OuiCunCercle.py


In [29]:
from OuiCunCercle import CunCercle

C1 = CunCercle(2)
print(C1.aire())

12.566370614359172


2 Un classique des exos sur les classes :
Le code `CunJeuDeCartes.py` crée une classe CunJeuDeCartes qui construit un jeu de 52 cartes :
1. Une carte est caractérisée par une valeur et une forme (coeur, carreau, pique, trèfle).
2. De plus les méthodes suivantes sont implémentées :
    * nom_carte : affiche le nom d’une carte de manière littérale, ex. “valet de coeur”.
    * battre : mélange le jeu de cartes.
    * afficher : affiche le jeu de cartes.
    * tirer : extrait une carte du jeu.
Testez ce code, comprenez le bien. Au point, en particulier, d’être capable de corriger le code faux que je
vais vous envoyer à part.

In [47]:
%%writefile CunJeuDeCartes.py
import numpy as np

class CunJeuDeCartes :
    couleurs = ["pique", "trèfle", "coeur", "carreau"]
    valeurs = ["as", "roi", "dame", "valet", "dix", "neuf", "huit", "sept", "six", "cinq", "quatre", "trois", "deux"]

    def __init__(self):
        P = []
        for c in self.couleurs :
            for v in self.valeurs :
                P.append(f'{v} de {c}')
        self.paquet = P

    def nom_carte(self, n:int)->str :
        return self.paquet[n]

    def afficher(self):
        print(str(self))

    def __str__(self)->str:
        return "Le paquet de cartes est :\n"+"\n".join(self.paquet)

    def battre(self):
        #pour mélanger les cartes on échange deux cartes aléatoiresment jusqu'à ce que le paquet soit mélangé.
        #un paquet de n cartes est en général bien mélangé après 2n échanges
        for i in range(2*len(self.paquet)):
            a,b = np.random.randint(0, len(self.paquet)),np.random.randint(0, len(self.paquet))
            self.paquet[a], self.paquet[b] = self.paquet[b], self.paquet[a]

    def tirer(self):
        if self.paquet :
            return self.paquet.pop(np.random.randint(0, len(self.paquet)))
        else :
            return "Le paquet est vide, impossible de tirer une nouvelle carte."

Overwriting CunJeuDeCartes.py


In [48]:
from CunJeuDeCartes import CunJeuDeCartes

J1 = CunJeuDeCartes()
J1.afficher()

Le paquet de cartes est :
as de pique
roi de pique
dame de pique
valet de pique
dix de pique
neuf de pique
huit de pique
sept de pique
six de pique
cinq de pique
quatre de pique
trois de pique
deux de pique
as de trèfle
roi de trèfle
dame de trèfle
valet de trèfle
dix de trèfle
neuf de trèfle
huit de trèfle
sept de trèfle
six de trèfle
cinq de trèfle
quatre de trèfle
trois de trèfle
deux de trèfle
as de coeur
roi de coeur
dame de coeur
valet de coeur
dix de coeur
neuf de coeur
huit de coeur
sept de coeur
six de coeur
cinq de coeur
quatre de coeur
trois de coeur
deux de coeur
as de carreau
roi de carreau
dame de carreau
valet de carreau
dix de carreau
neuf de carreau
huit de carreau
sept de carreau
six de carreau
cinq de carreau
quatre de carreau
trois de carreau
deux de carreau


In [49]:
J1.battre()
J1.afficher()

Le paquet de cartes est :
as de coeur
dame de coeur
deux de trèfle
sept de carreau
trois de trèfle
dix de pique
deux de coeur
neuf de carreau
deux de pique
as de trèfle
as de carreau
quatre de coeur
huit de carreau
dix de trèfle
roi de trèfle
cinq de trèfle
huit de coeur
huit de pique
quatre de pique
cinq de carreau
six de coeur
trois de pique
as de pique
sept de coeur
deux de carreau
valet de coeur
sept de trèfle
trois de coeur
roi de carreau
neuf de pique
dame de carreau
neuf de coeur
dix de coeur
valet de trèfle
dame de pique
trois de carreau
quatre de trèfle
quatre de carreau
sept de pique
six de trèfle
neuf de trèfle
dame de trèfle
roi de coeur
dix de carreau
roi de pique
valet de pique
valet de carreau
six de pique
huit de trèfle
six de carreau
cinq de pique
cinq de coeur


In [50]:
for i in range(53):
    print(J1.tirer())

deux de pique
huit de trèfle
quatre de coeur
quatre de carreau
roi de trèfle
neuf de trèfle
sept de coeur
dame de coeur
huit de pique
dame de pique
roi de coeur
dix de carreau
six de carreau
neuf de carreau
valet de coeur
sept de pique
cinq de carreau
trois de coeur
as de pique
six de trèfle
six de pique
six de coeur
roi de pique
valet de carreau
roi de carreau
deux de trèfle
as de trèfle
cinq de coeur
valet de pique
as de coeur
quatre de trèfle
trois de trèfle
dix de trèfle
huit de coeur
sept de trèfle
dix de coeur
dame de trèfle
as de carreau
deux de carreau
dix de pique
dame de carreau
cinq de pique
huit de carreau
neuf de coeur
trois de pique
deux de coeur
sept de carreau
cinq de trèfle
trois de carreau
valet de trèfle
neuf de pique
quatre de pique
Le paquet est vide, impossible de tirer une nouvelle carte.


voici le code faux avec les corrections :

In [34]:
%%writefile JeuDeCartesFaux.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jan 13 22:57:20 2019

@author: cchoquet
"""

import random

class Carte :#parenthèses inutiles
    
    def __init__(self, f, c): 
        self.figure = f 
        self.couleur = c #mauvaise tabulation
        
    def affiche (self):
        s = self.figure + " de " + self.couleur 
        return(s) #mauvaise tabulation

class JeuDeCartes (): 
    
    def __init__(self):
        couleur = ["Pique","Coeur","Carreau","Trèfle"]
        valeur = ["As","2","3","4","5","6","7","8","9","10","Valet","Dame","Roi"]
        #~ Construction de la liste des 52 cartes
        self.cartes=[]
        #boucle for mal indentée
        for coul in couleur: 
            for val in valeur: #replacement du while par un for
                self.cartes.append(Carte(val,coul))   #remplacement de + par la fonction append
        return

    #~ Mélange des cartes
    def battre(self): 
        random.shuffle(self.cartes)

    # Tirage la première carte de la pile
    def tirer(self):
        if ( len(self.cartes) == 0 ):
            print ("Plus aucune carte")
            return 
        else:
            t = random.randint(0, len(self.cartes)-1) 
            carte = self.cartes[t]
            del(self.cartes[t]) 
            return (carte)

    # Affichage du jeu de carte
    def afficher(self):
        #correction d'indentation
        for carte in (self.cartes):
            print (carte.affiche())

#Test :
#import CJeuDeCartes (inutile ici car un seul et même fichier)
#jeu = CJeuDeCartes.JeuDeCartes ()
jeu = JeuDeCartes ()            
jeu.afficher()
input ("Nous allons mélanger le jeu de cartes")
jeu.battre() 
jeu.afficher()
input ("Nous allons tirer les cartes une à une")
for i in range (52):
    c = jeu.tirer ()
    print ("Je viens de tirer la carte : %s" % (c.affiche()))

Overwriting JeuDeCartesFaux.py


In [35]:
%run JeuDeCartesFaux

As de Pique
2 de Pique
3 de Pique
4 de Pique
5 de Pique
6 de Pique
7 de Pique
8 de Pique
9 de Pique
10 de Pique
Valet de Pique
Dame de Pique
Roi de Pique
As de Coeur
2 de Coeur
3 de Coeur
4 de Coeur
5 de Coeur
6 de Coeur
7 de Coeur
8 de Coeur
9 de Coeur
10 de Coeur
Valet de Coeur
Dame de Coeur
Roi de Coeur
As de Carreau
2 de Carreau
3 de Carreau
4 de Carreau
5 de Carreau
6 de Carreau
7 de Carreau
8 de Carreau
9 de Carreau
10 de Carreau
Valet de Carreau
Dame de Carreau
Roi de Carreau
As de Trèfle
2 de Trèfle
3 de Trèfle
4 de Trèfle
5 de Trèfle
6 de Trèfle
7 de Trèfle
8 de Trèfle
9 de Trèfle
10 de Trèfle
Valet de Trèfle
Dame de Trèfle
Roi de Trèfle
Nous allons mélanger le jeu de cartes
8 de Carreau
Dame de Carreau
9 de Pique
8 de Trèfle
Dame de Coeur
6 de Pique
9 de Coeur
10 de Pique
5 de Pique
5 de Coeur
3 de Carreau
2 de Coeur
2 de Trèfle
5 de Carreau
6 de Carreau
4 de Trèfle
Roi de Pique
Dame de Pique
Valet de Coeur
Valet de Pique
10 de Trèfle
6 de Trèfle
Roi de Car

## 6. Exercice : un algorithme de tri

Observez bien ce monument : `bon_courage.mp4`

In [36]:
from IPython.display import Video

Video("img/bon_courage.mp4")

Il me faut un programme me permettant de faire tourner sur n’importe quel jeu de données (un ensemble
fini de nombres positifs non ordonné !). L’algorithme de tri correspondant EXACTEMENT à la vidéo !

*Indice* : Pour démarrer, un cas plus simple :
[lien vers Youtube en cliquant ici](https://www.youtube.com/watch?v=LriMvv9qDrk) qui correspond à :

<img src="img/tri_selection.png" alt="alt_text" align="left"/>

voici donc un algorithme de **tri par sélection** :

In [37]:
#on crée une liste et on la mélange
L = np.arange(24)
np.random.shuffle(L)

In [38]:
def tri_sélection(L:list)->list:
    for i in range(len(L)-1):
        i_min = i
        for j in range(i+1, len(L)):
            if L[j]<L[i_min] :
                i_min = j
        L[i], L[i_min] = L[i_min], L[i]
    return L

In [39]:
print(L)
print(tri_sélection(L))

[ 5  6  7 20 13 16 15  1 21  3 17  4  0  9 11 22 12 10  8 23 18 19  2 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


Et voici un algorithme de **tri rapide** avec créations de listes :

In [40]:
np.random.shuffle(L)

In [41]:
def tri_rapide(L:list)->list:
    if len(L)<=1 :
        return L
    else :
        curseur = L[0]
        petit = []
        egal = []
        grand = []
        
        for i in range(len(L)):
            if L[i]==curseur :
                egal.append(L[i])
            elif L[i]<curseur :
                petit.append(L[i])
            else :
                grand.append(L[i])
                    
        return np.array(list(tri_rapide(petit))+egal+list(tri_rapide(grand)), dtype=int)

In [42]:
print(L)
print(np.array(tri_rapide(L)))

[12 23 11 18 10 15 14  3  8  0 17  5 20  6 22 19  7  4  2  1 16  9 21 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


cependant on peut faire un tri qui se rapproche plus de la vidéo avec un **tri rapide en place** avec l'algorithme suivant :

In [43]:
np.random.shuffle(L)

In [44]:
def tri_rapide_en_place(L:list)->list:
    if len(L)<=1 :
        return L
    else :
        curseur = 0
        j = len(L)-1
        for i in range(len(L)):
            if j<curseur :
                if L[j]>L[curseur]:
                    L[j],L[curseur]=L[curseur],L[j]
                    j,curseur=curseur,j
                    j-=1
                else :
                    j+=1
            else :
                if L[j]<=L[curseur]:
                    L[j],L[curseur]=L[curseur],L[j]
                    j,curseur=curseur,j
                    j+=1
                else :
                    j-=1
        
        tri_rapide_en_place(L[:curseur])
        tri_rapide_en_place(L[curseur+1:])
        return L

In [45]:
print(L)
print(tri_rapide_en_place(L))

[15 12 16 19  5  6 11 18 20  2 10  3 13 21  8 17  1 22  4 23  7 14  0  9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
